#!/bin/sh
if [ -z "${GIT_USER}" ]; then
    GIT_USER=ejsa13
else
    GIT_USER="${GIT_USER}"
fi

if [ -z "${GIT_REPO}" ]; then
    GIT_REPO=pcfocp-poc
else
    GIT_REPO="${GIT_REPO}"
fi

if [ -z "${GIT_BRANCH}" ]; then
    GIT_BRANCH=main
else
    GIT_BRANCH="${GIT_REPO}"
fi

if [ -z "${GIT_FOLDER}" ]; then
    GIT_FOLDER=config-repo
else
    GIT_FOLDER="${GIT_FOLDER}"
fi

if [ -z "${GIT_FILE}" ]; then
    GIT_FILE=application.properties
else
    GIT_FILE="${GIT_FILE}"
fi

# should use token for security, this POC uses public repo
git_uri=https://raw.githubusercontent.com/$GIT_USER/$GIT_REPO/$GIT_BRANCH/$GIT_FOLDER/$GIT_FILE
echo $git_uri
curl -LJ $git_uri -o app.properties